### ISSUE TITLE
Doesn't work on the latest Nightlies

### ISSUE THREAD

**Issue by kubo25** [nt1m/vivaldi-fox#103]
Doesn't seem to work on at least the last 2 newest nightlies.

Gives this error when changing tabs:
`TypeError: currentTheme is undefined; can't access its "patch" property background.js:14:5`

And these when I disable and reenable it: 
`Error: Could not establish connection. Receiving end does not exist. contentscript.js:12:5` 
`Error: Could not establish connection. Receiving end does not exist. contentscript.js:5:5`
`Error: Could not establish connection. Receiving end does not exist. contentscript.js:12:5`
`vivaldifox: toRgb failed with color.js:11:7`
`TypeError: (new Color(...)).components is null; can't access its "join" property theme.js:85:27`
`vivaldifox: toRgb failed with color.js:11:7`

**Comment by eyepet2002** [comment]
Not working in stable builds either now.

**Comment by nt1m** [comment]
I'll give it a look when I have some time. I know what broke in Nightly, not sure about release though.

**Comment by eyepet2002** [comment]
Actually just checked, running beta version because firefox developer edition. Derp.
