### ISSUE TITLE
Conflicts with MaterialFox

### ISSUE THREAD

**Issue by DaniellMesquita** [nt1m/vivaldi-fox#104]
Do you know about the chrome folder that applies material design to Firefox?
It works with the VivaldiFox, but the addressbar is with white background and text

**Comment by nt1m** [comment]
Apparently it's an intentional choice from the MaterialFox author: https://github.com/muckSponge/MaterialFox/issues/9#issuecomment-426851434

**Comment by DaniellMesquita** [comment]
Could you make it compatible?

**Comment by DaniellMesquita** [comment]
Fixed in: https://github.com/muckSponge/MaterialFox/issues/95
