### ISSUE TITLE
Doesn't work with Tree Style Tab

### ISSUE THREAD

**Issue by Fantasycheese** [nt1m/vivaldi-fox#106]
Hey thanks for this awesome extension, it's really beautiful.
So the introduction on Firefox extension page states that it works with Tree Style Tab, does that mean the background and tab color of TST should adapt to current page like normal tab and navigation bar?
I have try both extension in a brand new profile but I can't get it work. Current version of Firefox is 64.0.2.

**Comment by evelyndooley** [comment]
Can confirm, for me TST won't pick up the color

**Comment by nt1m** [comment]
I filed https://github.com/piroor/treestyletab/issues/2221

**Comment by nt1m** [comment]
Piro just fixed this in https://github.com/piroor/treestyletab/commit/31a567f59e9f7192456f13de69fd107e7ee398a3
