### ISSUE TITLE
VivaldiFox changes firefox ui dark theme 

### ISSUE THREAD

**Issue by lenicyl** [nt1m/vivaldi-fox#117]
The extension is working great but there is one issue. Whenever i enable the extension it changes firefox's ui theme which is an effect i do not want. I have enabled dark theme in both VivaldiFox options and Firefox's themes, however it still gives me menus that are in light mode

 ![Screenshot 2021-04-30 083301](https://user-images.githubusercontent.com/73347143/116643638-1ef93c80-a98f-11eb-8053-18d32d903061.png)

- Firefox Version : 88.0
- VivaldiFox Version : 3.1

**Comment by nt1m** [comment]
There's a theme editor where you can edit the popup properties.  Have you tried it?

**Comment by Q-out** [comment]
Came here to report the same thing. But I'm glad VF is still working on the redesign at least.
Switching to any theme in Firefox enables it:
![image](https://user-images.githubusercontent.com/52709014/120665910-d0692180-c4a9-11eb-97a5-ca631e4b5359.png)
But then switching tabs reverts it to light colors even as it still shows that other theme as applied:
![image](https://user-images.githubusercontent.com/52709014/120666077-ed9df000-c4a9-11eb-8dfe-9364df5dd64f.png)


>There's a theme editor where you can edit the popup properties. Have you tried it?

Do you mean https://color.firefox.com? I tried it, the colors from it are instantly overwritten by VF — which is good normally but it means the white popups come back as well.

**Comment by videopilot** [comment]
It seems to somehow break the system theme detection used elsewhere. On Mac, it means other windows don't change to dark (now that FF added that recently). It also seems to sometimes break Dark Reader's auto dark detection.

![systemdark](https://user-images.githubusercontent.com/6528746/129453433-aaebb7e5-b6ec-49ae-b629-f4eabd71bbe0.gif)

**Comment by nt1m** [comment]
> > There's a theme editor where you can edit the popup properties. Have you tried it?
> 
> Do you mean https://color.firefox.com? I tried it, the colors from it are instantly overwritten by VF — which is good normally but it means the white popups come back as well.

Nope, I mean this, go to the add-ons manager and visit the VivaldiFox preferences:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/1795135/129453492-b943228e-0678-4e6e-b4e3-c986cff14473.png">

It brings you to this page:

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/1795135/129453523-c23acbd4-c508-4074-aef0-b2e32cdc62ae.png">

**Comment by videopilot** [comment]
It seems to break Firefox's system theme detection and changes. On Mac that affects other dialogs and pop up menus.

![systemdark](https://user-images.githubusercontent.com/6528746/129453701-be5f9908-77f3-44c7-9b6d-c5242b57c344.gif)

**Comment by nt1m** [comment]
yeah this was changed in Firefox 91: https://bugzilla.mozilla.org/show_bug.cgi?id=1715145

The dark theme follows the toolbar background color shade, so you could edit the toolbar background color to be dark?

Though you should file a bug on bugzilla if you don't want to do this, I can't really do anything about this.

**Comment by Q-out** [comment]
> Nope, I mean this, go to the add-ons manager and visit the VivaldiFox preferences:

Ah, I didn't realize editing the popup colours would edit the menu ...popup, which seems obvious now. Thank you, I've got my dark menus with a colourful navbar.
