### ISSUE TITLE
Keyboard Shortcut for Vivaldifox Addon Toggle

### ISSUE THREAD

**Issue by Gd-Gordon** [nt1m/vivaldi-fox#119]
Now when I need to switch off vivaldifox temporarily, I need to go to the addons page and scroll over and over to find the toggle for Vivaldifox. Can you add Firefox keyboard shortcut support for this addon so I can easily switch it on and off?

**Comment by nt1m** [comment]
There's a toolbar button you can use, and put in your overflow menu or your toolbar, which is probably faster than going to the add-ons page.

I might allow a keyboard shortcut to be added though

**Comment by nt1m** [comment]
@Gd-Gordon You can now set a shortcut in about:addons

<img width="985" alt="image" src="https://user-images.githubusercontent.com/1795135/140967473-3a039231-b9a9-4f26-b2ce-9d8f5c7921bd.png">

**Comment by Gd-Gordon** [comment]
Cool. Thanks for your work!
