### ISSUE TITLE
Compatibility with Beyond Australis

### ISSUE THREAD

**Issue by nt1m** [nt1m/vivaldi-fox#12]
https://github.com/Quicksaver/The-Fox--Only-Better by @Quicksaver

Right now, the navigation bar is not coloured with the add-on.

**Comment by Quicksaver** [comment]
This might help: https://github.com/Quicksaver/The-Fox--Only-Better/issues/24

**Comment by nt1m** [comment]
@Quicksaver Thanks ! I'm going to try this:

#theFoxOnlyBetter-slimChrome-toolbars,
#theFoxOnlyBetter-slimChrome-toolbars-before,
#theFoxOnlyBetter-slimChrome-toolbars-after {
  background-color: var(--theme-accent-background);
}

**Comment by Quicksaver** [comment]
You're very welcome, let me know if you need any extra help with it. :)

**Comment by nt1m** [comment]
Looks like the selected tab doesn't have the right text colour with the addon enabled.

**Comment by Quicksaver** [comment]
Anything I can do to help? I actually don't see this problem, the tab's text color changes between white and black accordingly with a darker or lighter background color for me as expected (that's what's expected right?).

I do see that it's not setting the ```brighttext``` attribute on the hidden toolbars properly. Maybe the ```ontransitionend``` listener it sets on the ```#nav-bar``` isn't firing? Although I'm not sure exactly what transition it is waiting for.

(BTW please test with the latest code from master if you can. Do you need me to upload a signed beta?)

**Comment by Quicksaver** [comment]
[Beta version 1.4.7b1](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.7b1) if you want it.

**Comment by nt1m** [comment]
Probably won't fix with the WebExtensions port: https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/beta
