### ISSUE TITLE
🪟 Glass || Transparency

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [nt1m/vivaldi-fox#121]
Is there any chance to get transparency or glass effect on tab bar if possible? or through `userChrome.css`?
Imagine a blurred transparency background in websites color saturation.

_VivaldiFox looks awesome as it is yet._

**Comment by nt1m** [comment]
This isn't possible with the current theme API, but is probably possible with `userChrome.css`, I recommend asking on https://reddit.com/r/firefoxcss/ .

**Comment by emvaized** [comment]
I think you could take a look at BlurredFox project. However, it was reported that it stopped working in recent Firefox versions.
https://github.com/manilarome/blurredfox
