### ISSUE TITLE
VivaldiFox cannot be set 

### ISSUE THREAD

**Issue by carrot-eggs** [nt1m/vivaldi-fox#122]
Hello, I'm using VivaldiFox, it makes Firefox look very beautiful, but after Firefox is updated to 94.0.1, VivaldiFox cannot be set up. I don't know how to solve it. Can you help me see this problem? thank you very much.
![图片](https://user-images.githubusercontent.com/35254441/142237226-9672b3ef-a6e4-40d9-aabd-ee2a3d4ac53d.png)

**Comment by nt1m** [comment]
@carrot-eggs Thanks for reporting! Do you see errors in the [Browser Console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) or the Web Console (Ctrl+Shift+K)?
