### ISSUE TITLE
Compatibility with CTR

### ISSUE THREAD

**Issue by nt1m** [nt1m/vivaldi-fox#13]
https://github.com/Aris-t2/ClassicThemeRestorer by @Aris-t2

Right now the tab settings are incompatible, and the colouring doesn't apply to CTR squared tabs.

**Comment by Aris-t2** [comment]
There is no way to avoid glitches when two add-ons try to style tabs at the same time, but CTR offers a way to set default tabs for "Vivaldi-fox" to work properly.
CTRs prefwindow > Tabs (1) > Tabs > [first menulist] > Firefox default (curved tabs)

**Comment by nt1m** [comment]
Not relevant with the WebExtension version: https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/beta
