### ISSUE TITLE
[Feature Request] Extend the addon's functionality to the behavior of tabs

### ISSUE THREAD

**Issue by A-7666** [nt1m/vivaldi-fox#130]
Thank you for a great extension! :-) 

I am moving to a Firefox-based browser, and the problem here is that I cannot stand how tabs behave.
When there are many tabs they don't shrink and are not all visible, and one has to scroll the tab bar to the right-left, which is very uncomfortable.
Unlike how it was in Opera Presto (and later in Chromium-based browsers, including Vivaldi), where they shrink / are reduced in width and are all visible no matter how many tabs there are.
(In addition to this, Vivaldi can set the minimal width for the active tab (I was setting it to 120/150px), so that the active tab is not shrunk and its title is visible on the tab).

I'm not aware of any FF addon that can do this,
And it would be awesome to have this feature in VivaldiFox, to have an option to switch from FF-like tab behavior to Opera Presto/Chromium/Vivaldi-like tabs behavior.
Is there any chance for this feature to be added?

**Comment by nt1m** [comment]
This is something Firefox extensions cannot do unfortunately. There are probably some userChrome scripts out there that do this however.
