### ISSUE TITLE
Compatibility with NoScript

### ISSUE THREAD

**Issue by WindfallProphet** [nt1m/vivaldi-fox#15]
Color changing doesn't happen and/or is buggy when NoScript is installed. 

Tested on Dev Edition.

**Comment by nt1m** [comment]
@WindfallProphet Can you try the latest version (1.1.4) see if it's fixed for you ? https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/

**Comment by WindfallProphet** [comment]
Sorry, forgot to close this. Changes made with Noscript and it's improved e10s compat. fixed the issues for me.
