### ISSUE TITLE
Not working on Linux Mint 17.3 Cinnamon

### ISSUE THREAD

**Issue by steamolator** [nt1m/vivaldi-fox#17]
Hey, its not working on my System: Linux Mint 17.3 Cinnamon and FireFox 47.

`10:54:54.528 vivaldi-fox:TypeError: win is null
Stack-Trace:
setColour@resource://gre/modules/commonjs/toolkit/loader.js -> resource://vivaldi-fox/index.js:77:9
onTabChange@resource://gre/modules/commonjs/toolkit/loader.js -> resource://vivaldi-fox/index.js:31:7
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
tabEmit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:263:31
tabEventListener@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:328:23
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
initialize/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/observer.js:50:11
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
handleEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/observer.js:109:5
updateCurrentBrowser@chrome://browser/content/tabbrowser.xml:1154:15
onselect@chrome://browser/content/browser.xul:1:44
set_selectedIndex@chrome://global/content/bindings/tabbox.xml:668:13
set_selectedPanel@chrome://global/content/bindings/tabbox.xml:687:13
set_selectedIndex@chrome://global/content/bindings/tabbox.xml:403:15
set_selectedItem@chrome://global/content/bindings/tabbox.xml:435:34
_selectNewTab@chrome://global/content/bindings/tabbox.xml:480:11
onxblmousedown@chrome://global/content/bindings/tabbox.xml:802:11
1 core.js:106
`

**Comment by nt1m** [comment]
@steamolator Thanks for reporting! Does this build fix it for you : https://github.com/nt1m/vivaldi-fox/raw/master/%40vivaldi-fox-1.1.5.xpi ?

**Comment by steamolator** [comment]
Thanks it works now, looks great

**Comment by nt1m** [comment]
@steamolator Mysterious error... Not sure what's going on. Do you get any other error ?

**Comment by steamolator** [comment]
@nt1m that error seems to be gone. I get only this error now:

`16:47:49.033 TypeError: aWindow is undefined
_getTabForContentWindow() tabbrowser.xml:394
getBrowserForDocument() tabbrowser.xml:361
window.InstantFox.addEngine_() instantfox.js:10
DOMLinkHandler.addSearch() browser.js:3378
DOMLinkHandler.receiveMessage() browser.js:3356
1 tabbrowser.xml:394:17
`

**Comment by nt1m** [comment]
@steamolator The error seems linked to InstantFox. I've tried installing it, and it doesn't seem to break VivaldiFox on my side. I've also tried installing the add-ons you've listed on reddit, and I'm having no luck reproducing the issue.

Any chance you provide a screenshot ? Does it work on a blank profile ?

**Comment by steamolator** [comment]
@nt1m hey, everything looks fine on a blank profile. Sorry for the inconvenience. I will let update my poste when i find out what causes my problem. 

great add-on
