### ISSUE TITLE
Bright bakcground colors in dark theme makes the text unreadble.

### ISSUE THREAD

**Issue by Nidre** [nt1m/vivaldi-fox#19]
An option to use dimmed/darkened or not as bright colors might solve the issue?

http://i.imgur.com/RfBz8OD.png
http://i.imgur.com/oKPvvy5.png

**Comment by nt1m** [comment]
Strange, the text colour should change to black (at least it does for me)

**Comment by Nidre** [comment]
Anything I can do to provide some more info to hep you fix it ? :)

**Comment by nt1m** [comment]
@Nidre Thanks for reporting! :) 
Does it work on a new profile ? Do you see any errors in the browser console (Ctrl+shift+J)?
Do you have any other add-on installed ?

**Comment by Nidre** [comment]
@nt1m 

Disabling Beyond Australis fixes the problem.

**Comment by nt1m** [comment]
That's issue #12 then :)
