### ISSUE TITLE
"Preferences" button in the add-on manager should point to the right page

### ISSUE THREAD

**Issue by Nidre** [nt1m/vivaldi-fox#20]
1.1.5 on FF 50.0a1 (2016-06-18) doesn't let me edit theme selection on settings UI. I've had to use about:config to change it.

**Comment by nt1m** [comment]
Thanks for reporting!
Do you see any error in the console ?
What is the value of extensions.@vivaldi-fox.themes and extensions.@vivaldi-fox.selected-theme ?

**Comment by Nidre** [comment]
extensions.@vivaldi-fox.themes: []
extensions.@vivaldi-fox.selected-theme: dark (I've changed this manually on about:config since the options UI didn't let me)

I've got a few errors while trying to type on theme text box but not sure if they are related to vivaldifox.

13:46:35.101 ReferenceError: Application is not defined
<anonymous>allinonegestOverlay.js:2300
1allinonegestOverlay.js:2300:7

13:46:37.122 TypeError: can't access dead object1(unknown)

13:46:45.439 ReferenceError: Application is not defined
<anonymous>allinonegestOverlay.js:2300
1allinonegestOverlay.js:2300:7

13:47:13.348 TypeError: can't access dead object1(unknown)

13:47:37.872 ReferenceError: Application is not defined
<anonymous>allinonegestOverlay.js:2300
1allinonegestOverlay.js:2300:7

**Comment by nt1m** [comment]
You seem to be using the preference screen provided by the add-on manager. It's not well-tested yet.

**Comment by nt1m** [comment]
It is partially my fault that the "Preferences" button doesn't point to the right page though :)

**Comment by Nidre** [comment]
Btw it was working in one of the previous builds. I think it was the one that with the Beyond Australis compatibility implementation.

**Comment by nt1m** [comment]
@Nidre, does it work if you use the preferences screen provided by VivaldiFox ? (You need to click on the vivaldi fox toolbar button to access it)

**Comment by Nidre** [comment]
@nt1m I'm not sure if I have that toolbar button. Checked the customize screen, hamburger menu and title bar for it but couldn't find it :)

**Comment by nt1m** [comment]
It looks like this:
<img width="427" alt="vivaldifox addonbutton" src="https://cloud.githubusercontent.com/assets/1795135/16176934/e30bbb4c-361d-11e6-96a3-ad7598dad1ec.png">

**Comment by Nidre** [comment]
@nt1m 

I don't think I have it.

http://i.imgur.com/jWvviWr.png
http://i.imgur.com/dVT3SPY.png

**Comment by nt1m** [comment]
Hmm, that's really strange

**Comment by Nidre** [comment]
@nt1m 

Got it now, re-installed the addon. It opened a different UI page it seems to be working.

**Comment by nt1m** [comment]
@Nidre, does the button disappear if you restart Firefox ? If so, do you get any error ?

**Comment by nt1m** [comment]
Depends on mozilla-jetpack/jpm#543
