### ISSUE TITLE
Option: Disable loading browser.css

### ISSUE THREAD

**Issue by DarthTealc** [nt1m/vivaldi-fox#22]
An option to disable loading resource://vivaldi-fox/data/browser.css would be useful to allow custom themes/userstyles to use the CSS variables generated by Vivaldi-fox. Great addon btw!

**Comment by nt1m** [comment]
@DarthTealc, v1.2 provides this ability: https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/

I'm also curious of how you're going to customise the theme. Can you share a screenshot once your theme is done ?

**Comment by riedel** [comment]
After reading this, I created an example here from a user style (see comments for screenshot): https://gist.github.com/riedel/38a9c331dec54a1d1d955e3cb4c38669

cool feature!
