### ISSUE TITLE
provide vivaldifox webextension

### ISSUE THREAD

**Issue by rhelmer** [nt1m/vivaldi-fox#24]
As discussed here:
https://www.reddit.com/r/firefox/comments/4nvm27/initial_release_of_vivaldifox_with_autocolouring/d487jox

I think we should propose and build an API for the Firefox WebExtensions API to allow the core vivaldi fox feature, that is, setting the background of the browser chrome to an arbitrary color.

Let's chat about it here and then file bug(s) on the mozilla side when we're reasonable confident about our proposal.

**Comment by rhelmer** [comment]
I've been looking over the Chrome extension API to see if they allow anything like this, and where it might fit if so:
https://developer.chrome.com/extensions/api_index

The closest thing they provide is Chrome themes, which are similar to lightweight themes - you specify theme images and colors for the toolbar, tab background, etc. in the `manifest.json`.

I wonder if it would make sense to build a WebExtension API that allows modifying the theme at runtime, changing the color and images etc?

**Comment by nt1m** [comment]
Work is going on here: https://github.com/nt1m/WebExtensions-Theming-API/blob/master/Proposal.md

**Comment by nt1m** [comment]
@rhelmer I won't be available until Thursday (exams), but I've granted you push access to the WebExtensions-Theming-API repo. Feel free to add/modify proposals in the repo.

**Comment by nt1m** [comment]
All the APIs are needed so, I'll file an checklist issue for porting to WE.

**Comment by nt1m** [comment]
Filed #40
