### ISSUE TITLE
It seems doesn't work with my Firefox 48 b1 on Windows 10

### ISSUE THREAD

**Issue by ershiwo** [nt1m/vivaldi-fox#25]
Umm...I have install a pure firefox without any addons in a pure Windows 10 vm, but it also doesn't work. And I can't see the addon icon in custom tab or  any other place.
![2016-06-20_213846.png](https://c.hime.io/images/l5QvxVEp.png)
Color of tabs don't change.
![2016-06-20_214456.png](https://c.hime.io/images/eZjvOPZm.png)
Could you tell me how to use this addon? Thanks a lot.

**Comment by nt1m** [comment]
Do you get errors in the browser console (ctrl shift j) ?

**Comment by ershiwo** [comment]
Yes, there is.
![2016-06-20_215003.png](https://c.hime.io/images/3EMVXpZO.png)
![2016-06-20_215353.png](https://c.hime.io/images/y1JKRj50.png)

**Comment by nt1m** [comment]
Oh,wait, I see the issue. Gonna fix it right away

**Comment by nt1m** [comment]
@ershiwo Let me know if the latest version (v1.2.3) works : https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/

**Comment by Niamor** [comment]
I have the same issue, v1.2.3 doesn't fix it.
It also breaks pin tabs.

console : 
![firefox_2016-06-20_20-54-03](https://cloud.githubusercontent.com/assets/30397/16206545/3283d324-3729-11e6-94d5-071e953b287d.png)

**Comment by nt1m** [comment]
@Niamor Thanks, will take a look

**Comment by nt1m** [comment]
@Niamor, @ershiwo, ok I'm fairly sure it's fixed now in v1.2.4: https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/

**Comment by Niamor** [comment]
v1.2.5 seems to be working just fine for me.

**Comment by nt1m** [comment]
@Niamor Filed issue #26

**Comment by ershiwo** [comment]
@nt1m Now the new version works fine on my firefox. Thanks for your working :)
