### ISSUE TITLE
[Squared tabs] Fix pinned tabs

### ISSUE THREAD

**Issue by nt1m** [nt1m/vivaldi-fox#26]

**Comment by nt1m** [comment]
@Niamor One workaround is to use Australis tabs.

**Comment by Niamor** [comment]
I didn't realize it was only for Squared tabs sorry, option that I only tried today actually... I am now back to using Australis tabs and it is working just fine.

**Comment by nt1m** [comment]
@Niamor It is a valid issue for squared tabs. You deserve the credit for finding the bug :)
