### ISSUE TITLE
v1.2.2 and v1.2.5 - settings can't be changed and toolbar button does not appear

### ISSUE THREAD

**Issue by AmperAndSand** [nt1m/vivaldi-fox#27]
In versions: 1.2.2 and 1.2.5 I can't change the settings in Add-ons → VivaldiFox → Options. Checking or unchecking does not change the default settings.

Also, the VivaldiFox toolbar button does not appear, even if I tried to go to the 'Customize' toolbar menu to find it. However, when I downgraded to v1.1.5, I don't get any of these issues and it works fine.

This is on Firefox 47.0 64-bit, on Windows 7.

**Comment by nt1m** [comment]
Errors in the console (Ctrl+Shift+J) ?

**Comment by nt1m** [comment]
Also, what's the value of extensions.@vivaldi-fox.themes and extensions.@vivaldi-fox.selected-theme in about:config ?

**Comment by AmperAndSand** [comment]
@nt1m I've updated VivaldiFox to 1.2.5 from 1.1.5 and I can't seem to reproduce the issue anymore. Feel free to mark this as closed.
