### ISSUE TITLE
Clicking behind the tabs cause the tab color to flicker

### ISSUE THREAD

**Issue by bull500** [nt1m/vivaldi-fox#28]
STR:
1. Have an open tab which shows the color on the tab. Keep this tab selected.
2. Click on background and notice the color of the tab flicker

**Comment by bull500** [comment]
I think ill keep this another minor issue as well here; because its not consistently reproducible 
Hit 'PrntScr' on keyboard and wait for it to screenshot on Linux. Tab flicker occurs here as well.  
Sometimes in the file you'll save correctly with the tab color and other time you do not.

**Comment by nt1m** [comment]
@bull500 Thanks for reporting! Do these bugs occur if you turn off the "Grey out inactive windows" option?

**Comment by bull500** [comment]
@nt1m ah no! 
Should have checked out that option! 😅

**Comment by nt1m** [comment]
@bull500 Looks like clicking the area behind the tab/taking a screenshot seems to be making the window inactive on your platform. I can't do anything about this :/ Sorry.

You can  turn off the "Grey out inactive windows"  if that bothers you :)
