### ISSUE TITLE
Icons becomes unreadable, doesn't update depending on the new color

### ISSUE THREAD

**Issue by Nidre** [nt1m/vivaldi-fox#30]
For example those icons are very hard to read. They should've been switched to white when the background is dark.

![image](https://cloud.githubusercontent.com/assets/6220948/17118858/6e34ab2e-52cb-11e6-8ff0-3ffd9f426e82.png)

**Comment by nt1m** [comment]
@Nidre Same as #29 I can't reproduce this one either

**Comment by Nidre** [comment]
@nt1m 

Anything else I can do  to help? I guess Beyond Australis might be conflicting again, Previous similar issues were related to Beyond Australis extension.

Firefox version: 50.0a1 (2016-07-23)
OS Windows 10 10586.494

Extensions
----------

Name: Activity Stream
Version: 1.1.0
Enabled: true
ID: @activity-streams

Name: Add to Search Bar
Version: 2.9
Enabled: true
ID: add-to-searchbox@maltekraus.de

Name: Beyond Australis
Version: 1.4.6
Enabled: true
ID: thefoxonlybetter@quicksaver

Name: Buffer
Version: 2.13.28
Enabled: true
ID: jid1-zUyU7TGKwejAyA@jetpack

Name: checkCompatibility
Version: 1.3.1-signed.1-signed
Enabled: true
ID: check-compatibility@dactyl.googlecode.com

Name: Decentraleyes
Version: 1.3.5
Enabled: true
ID: jid1-BoFifL9Vbdl2zQ@jetpack

Name: Firefox Hello
Version: 1.4.3
Enabled: true
ID: loop@mozilla.org

Name: FloatView
Version: 1.2.4.9.1-signed.1-signed
Enabled: true
ID: jid1-NdaSiRJQjdPtJg@jetpack

Name: FlyWeb
Version: 1.0.0
Enabled: true
ID: flyweb@mozilla.org

Name: HTTPS-Everywhere
Version: 5.2.1
Enabled: true
ID: https-everywhere@eff.org

Name: Imagus
Version: 0.9.8.45
Enabled: true
ID: {00000f2a-7cde-4f20-83ed-434fcb420d71}

Name: LastPass
Version: 4.1.20a
Enabled: true
ID: support@lastpass.com

Name: Mouse Gestures Suite
Version: 2.4.0
Enabled: true
ID: mousegesturessuite@lemon_juice.addons.mozilla.org

Name: Multi-process staged rollout
Version: 1.0
Enabled: true
ID: e10srollout@mozilla.org

Name: Open Tabs Next To Current Plus
Version: 1.0.4
Enabled: true
ID: opentabsnexttocurrentplus@nidre

Name: Pin It button
Version: 1.37.9
Enabled: true
ID: jid1-YcMV6ngYmQRA2w@jetpack

Name: Pocket
Version: 1.0.4
Enabled: true
ID: firefox@getpocket.com

Name: Quick Context Search
Version: 1.5.4
Enabled: true
ID: quickcontextsearch@pf

Name: Reddit Enhancement Suite
Version: 4.6.1
Enabled: true
ID: jid1-xUfzOsOFlzSOXg@jetpack

Name: Restart
Version: 1.2.8
Enabled: true
ID: Restart@schuzak.jp

Name: Save File to
Version: 2.5.5
Enabled: true
ID: savefileto@mozdev.org

Name: Stylish
Version: 2.0.6
Enabled: true
ID: {46551EC9-40F0-4e47-8E18-8E5CF550CFB8}

Name: Test Pilot
Version: 0.8.0-tag-2016-07-15-1
Enabled: true
ID: @testpilot-addon

Name: trello-card-numbers
Version: 1.0.1-signed.1-signed
Enabled: true
ID: jid1-jvS1Yxjh3c6VUw@jetpack

Name: uBlock Origin
Version: 1.7.7b15
Enabled: true
ID: uBlock0@raymondhill.net

Name: Web Compat
Version: 1.0
Enabled: true
ID: webcompat@mozilla.org

Name: ZenMate Security, Privacy & Unblock VPN
Version: 5.5.3
Enabled: true
ID: firefox@zenmate.com

Name: Art Project
Version: 0.1.4
Enabled: false
ID: jid1-2owcJCGUIo2yBA@jetpack

Name: FindBar Tweak
Version: 2.1.10
Enabled: false
ID: fbt@quicksaver

Name: VivaldiFox
Version: 1.2.6
Enabled: false
ID: @vivaldi-fox

**Comment by nt1m** [comment]
This issue is triggered by Beyond Australis, one thing you can try is revert to an earlier version of that addon. Still not sure where #29 comes from

**Comment by nt1m** [comment]
It's going to take a while before I can fix both issues unfortunately.
I see 2 temporary solutions for you:
- Uncheck "Use add-on stylesheet (browser.css)" and create your own userstyle (you can using var(--theme-accent-background) for the page colour, and var(--theme-secondary-background)
- Revert to an older version of "beyond australis"

**Comment by Nidre** [comment]
@nt1m 

Fair enough I will take a look at them.

**Comment by nt1m** [comment]
Not relevant with the WebExtension version: https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/beta
