### ISSUE TITLE
multi-window issues.

### ISSUE THREAD

**Issue by typetonk2** [nt1m/vivaldi-fox#31]
**Version:**

```
VivaldiFox: 1.2.6
Firefox: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0
```

**Description:**

When you restart firefox when multi-window exists, problem will occur.
1. Option window is incorrect.
2. Is not correct TAB-color also check the "Use Page Colours for UI".

**Expected behavior:**
1. Option window will be displayed correctly.
2. TAB-color will be changed by page UI.

**Steps to reproduce:**
1. The "When Firefox starts" option is set to "Show my windows and tabs from last time".
2. Install VivaldiFox.
3. Restart when multi-window exists.
4. Open to VivaldiFox option window.

**Comment by nt1m** [comment]
Thanks for the report!
I can't reproduce this locally. Does it happen on a blank profile? Any errors in the Browser Console?

**Comment by typetonk2** [comment]
Hi nt1m.
Yes, this issue happen on blank profile.
I used FirefoxPortable, tried a new(blank) profiles.
The following messages had been output to Browser Console.

![20160829231731-browser console](https://cloud.githubusercontent.com/assets/1439590/18054470/00013520-6e3f-11e6-8df2-d6650d760ccb.jpg)

Best Regards.

**Comment by nt1m** [comment]
@typetonk2 Sorry for the very late reply, does this still happen with VivaldiFox 1.2.7 ?
https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/

**Comment by typetonk2** [comment]
Hi, sorry for late reply.
I tried VivaldiFox 1.2.8 + FirefoxPortable 49.0.1, but still happen.

I tried steps below.

1. Download Firefox Portable, and add the VivaldiFox.
1. run `FirefoxPortable.exe`.
1. Click `Tools->Options`.
1. Change option `When Firefox starts` to `Show my windows and tabs from last time`.
1. Click `File->New Window`.
1. Click `Tools->Add-ons` on the new window..
1. Click `VivaldiFox->Options`.
  * Now, two window is open, and tab color is red.
1. Click `File->Exit`.
1. run `FirefoxPortable.exe`.
  * Opens two window, show the tab of "VivaldiFox Option".
  * Tab color is not red, and option is incorrect.

**screen shot**

step7.
![20161028010657-cortana](https://cloud.githubusercontent.com/assets/1439590/19775273/e12b3b4c-9caa-11e6-88fb-511bc6ce5097.jpg)

step9.
![20161028010020-](https://cloud.githubusercontent.com/assets/1439590/19775059/1c072222-9caa-11e6-8eeb-ea3578767f72.jpg)

**Comment by nt1m** [comment]
Thanks! I've been able to reproduce this once on Windows, will investigate once I'm free from the 16th.

**Comment by nt1m** [comment]
I've fixed the issue in my newest update. It should be approved by Mozilla in the coming days.
