### ISSUE TITLE
Please remove blue line with DevTools theme

### ISSUE THREAD

**Issue by andreicristianpetcu** [nt1m/vivaldi-fox#34]
Hi,

I use [DevTools theme](https://addons.mozilla.org/en-US/firefox/addon/devedition-theme-enabler/) with VivaldiFox and I set the "Use Australis Tabs" to be unchecked. The current tab gets the color from VivaldiFox and this is nice but there is a one pixel line between the tab and the location bar that is blue. I think this is from DevEdition theme. Please remove it and set it to the same color as the tab.

![screenshot from 2016-12-03 14-39-39](https://cloud.githubusercontent.com/assets/922368/20859397/e92b0ff6-b966-11e6-84e9-2f7c8c9d090c.png)

I added a print screen to see how it looks.

**Comment by nt1m** [comment]
Fixed by a9db28b
I don't usually support custom configurations like this one, but the fix was simple enough.

**Comment by andreicristianpetcu** [comment]
Thank you! @nt1m

**Comment by andreicristianpetcu** [comment]
I just made a small donation for this :D

**Comment by nt1m** [comment]
@andreicristianpetcu Thanks! I appreciate it :)

**Comment by andreicristianpetcu** [comment]
Glad to help and support the project :)

I have a small question: when will this fix land in an official, signed, AMO release?

**Comment by andreicristianpetcu** [comment]
Nevermind..... I just signed my own unlisted addon and I will wait for the fix in your version :)
[myvivaldifox-1.2.9-fx.xpi.zip](https://github.com/nt1m/vivaldi-fox/files/629250/myvivaldifox-1.2.9-fx.xpi.zip)

**Comment by nt1m** [comment]
@andreicristianpetcu There's a version that is getting reviewed by Mozilla at: https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/
