### ISSUE TITLE
Border color of Address bar can't be changed

### ISSUE THREAD

**Issue by notnsane** [nt1m/vivaldi-fox#38]
I need to change the #000000 to a more eye-friendly grey, or a color that can synergize a bit better with the rest of my themes.

Can we get another additional color entry in the add-on?

Thanks for the wonderful extension!

**Comment by nt1m** [comment]
Can you share a screenshot ? I'm not seeing #000000 as border of my address bar, do you have another theme enabled ?

**Comment by nt1m** [comment]
@notnsane Can you check if the webextensions version is better ? https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/beta

**Comment by Madis0** [comment]
Can confirm that it is not #000000, but some semi-transparent gray value. Customizable would still be better, though 😛

**Comment by Madis0** [comment]
An example of something that could be done when this option was added:

![](http://i.pi.gy/0PabV.png)

(here done by a [userChrome.css tweak](https://github.com/Madis0/UserChrome-Tweaks/blob/a2c1d8b9b15f079edb8f688a32febd606eb6dd37/navbar/borderless-fields.css))

**Comment by nt1m** [comment]
The border color can't be changed by webextensions at the moment, I'll file a bug to add this in the theming API

**Comment by nt1m** [comment]
It's now changeable from WebExtensions in Firefox 59: https://bugzilla.mozilla.org/show_bug.cgi?id=1418603

Removing `themingapi` tag.

**Comment by nt1m** [comment]
Here's a beta version with this feature: https://github.com/nt1m/vivaldi-fox/releases/tag/v3.0b1
