### ISSUE TITLE
www.pizzaladonna.ro freezes Firefo for 10 seconds

### ISSUE THREAD

**Issue by andreicristianpetcu** [nt1m/vivaldi-fox#39]
Hi,

[Pizzaladonna](http://www.pizzaladonna.ro/)'s web site freezes the whole browser for about 10 seconds. Please see the GIF file.

![pizzaladonna](https://cloud.githubusercontent.com/assets/922368/23625170/206e5c66-02a0-11e7-9a67-39b1028516cd.gif)

I created a new Firefox profile (tested both in stable v51 and in Nightly 54) and Vivaldifox is the only addon I have. I'm using Fedora 25.

I don't buy pizza that often but it would be nice for this issue to get fixed :D 

Thank you for building Vivaldifox

**Comment by nt1m** [comment]
Thanks for reporting! It seems like the icon on this website is huge (2074*1088): http://www.pizzaladonna.ro/wp-content/uploads/2014/06/PizzaLadonnaLogofinal.png , which is why the browser seems to freeze for a few seconds.

**Comment by nt1m** [comment]
@andreicristianpetcu I have a fix in hand that gives a maximum size of 128px for icons, but unfortunately, it seems to change the color when processing (which is expected, since it has less pixels to process).

One way to get closer to the old color is increasing the maximum icon size.

![Uploading old-vs-new.png…]()

**Comment by nt1m** [comment]
Increasing the maximum size to 256 seems to keep the old color (without any noticeable perf drawback on my side). According to my tests, you start to get a (small) noticeable freeze above 700px. So I guess I'll push 256 for now.

**Comment by andreicristianpetcu** [comment]
Thank you! I'm waiting for the update :D

**Comment by nt1m** [comment]
@andreicristianpetcu I published a new version on AMO, it's undergoing review, but if you can't wait, here [it is](https://github.com/nt1m/vivaldi-fox/blob/master/vivaldi-fox.xpi ) :)
