### ISSUE TITLE
WebExtensions port 

### ISSUE THREAD

**Issue by nt1m** [nt1m/vivaldi-fox#40]
https://github.com/nt1m/vivaldi-fox/tree/webextension

- [x] meta tag fetching
- [x] favicon-color fetching (`tabs.Tab.favIconUrl`)
- [ ] UI Settings (Gray inactive windows + Use page colours + Opacity settings)
- [x] Theme settings (I'll probably provide something a bit more flexible than now)
- [ ] expose an API for other webextensions (to set/get colors)

**Comment by andreicristianpetcu** [comment]
I could not [help myself from signing it and using it](https://github.com/andreicristianpetcu/chrome2firefox/releases/download/v0.0.1/unofficial_vivaldifox_webextension-2.0-an.fx.xpi) :D 

It's pretty awesome as it is!

**Comment by Madis0** [comment]
I love how it styles the frame instead of toolbar, the XUL version custom themes nor [userstyle workarounds](https://userstyles.org/styles/137066/vivaldifox-square-tabs) never worked for me on GNOME. Thank you, @andreicristianpetcu!

**Comment by marsjaninzmarsa** [comment]
Thoughts about AMO distribution as [beta version](https://developer.mozilla.org/en-US/Add-ons/Distribution#Beta_versions)?

**Comment by nt1m** [comment]
@marsjaninzmarsa It's not quite ready yet. Settings are not implemented atm, but once that's done I will publish a beta version.

**Comment by nt1m** [comment]
An update on the WebExtension:
The backend for most features is implemented, what's remaining is the implementation of the settings (so those features can actually be controlled by the user).

Once that's done, I'll publish a beta on AMO for testing.

I can't wait to share all the new features (yes, there will be new features 😄 ) coming in the WebExtension!

**Comment by andreicristianpetcu** [comment]
@nt1m do you happen to have a Bitcoin wallet? :)
You are doing a lot of cool stuff for Firefox users.

**Comment by nt1m** [comment]
A beta is out on AMO: https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/beta !
Please help me test it, and report any issues here :)

**Comment by nt1m** [comment]
@andreicristianpetcu You can try sending them to `1HAcvcoqQfgC7uVpLiGAee7NTFneNfYyCH` :)

**Comment by Findus23** [comment]
@nt1m many thanks for the update.

Unfortunatly it doesn't seem to be working for me. The tab bar gets kind of semi-transparent but stays grey.
I get the following error on every tab change
```
Error: Could not establish connection. Receiving end does not exist. 
Error: Incorrect argument types for theme.update.
```
![screenshot_20171108_195556](https://user-images.githubusercontent.com/6266037/32568582-00412ce8-c4bf-11e7-9351-ce507fc78c8c.png)

Is it possible that the needed API was only added in Firefox 57?
(I am using Firefox 56.0 from Debian Sid, so maybe this is just a bug in my Firefox version)

**Comment by nt1m** [comment]
@Findus23 Ah, yes the add-on only works on 57+ (due to missing APIs in 56).

Thanks for testing :)

**Comment by andreicristianpetcu** [comment]
Closed the issue? Should we be expecting a non-legacy one in AMO soon? Currently it is legacy https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/

**Comment by nt1m** [comment]
@andreicristianpetcu It is on the beta channel: https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/beta :)

It seems stable enough for a release now, but I'm rolling it out in beta so I can get some testing before releasing it to more people.

**Comment by andreicristianpetcu** [comment]
Waaaaaa! There are a few more options! :D Pretty nice!

Can I dim the color to make it less vibrant? The site colors is too strong. The old version had this feature.

**Comment by nt1m** [comment]
@andreicristianpetcu Glad you like it!

> Can I dim the color to make it less vibrant? 

I haven't implemented this yet. The built-in `<input type="color">` doesn't support alpha colors :/
I'll probably need to resort to using [`react-color`](https://casesandberg.github.io/react-color/) (the options page uses react).

**Comment by andreicristianpetcu** [comment]
can't wait for this change :D
