### ISSUE TITLE
Full Screen Colour change

### ISSUE THREAD

**Issue by MJPalmtree** [nt1m/vivaldi-fox#42]
On a mac air running Sierra, when I go full screen in Firefox the background/unfocused tabs change colour from my chosen theme to a very light grey. See attached screen shots. 

First image is the correct colours 
![screen shot 2017-04-09 at 21 41 58](https://cloud.githubusercontent.com/assets/27162291/24840863/aeaba96a-1d6d-11e7-82d8-55f79f4db5f7.png)

Second is what happens when I go full screen. 
![screen shot 2017-04-09 at 21 42 10](https://cloud.githubusercontent.com/assets/27162291/24840862/aea8b32c-1d6d-11e7-9c50-9a85d3e94cb5.png)

**Comment by nt1m** [comment]
I've fixed the issue in my newest update. It should be approved by Mozilla in the coming days.
