### ISSUE TITLE
Unable to access VivaldiFox addon options page

### ISSUE THREAD

**Issue by bull500** [nt1m/vivaldi-fox#47]
Error:  

Access to the file was denied
The file at resource://vivaldi-fox/data/options.html is not readable.

Ubuntu - FF 56.0a1 (2017-07-28) (64-bit)

**Comment by nt1m** [comment]
Thanks!

**Comment by bull500** [comment]
Looks like a sandbox problem. 
Affects test-pilot as well. Setting "security.sandbox.content.level" to 0 is a workaround

**Comment by nt1m** [comment]
I'll likely fix this with the WebExtensions port.
