### ISSUE TITLE
firefox 55 support

### ISSUE THREAD

**Issue by aakay** [nt1m/vivaldi-fox#48]
Hi Tim,

I know, you are working on porting the theme to WebExtension (I appreciate that, btw), but maybe it's a quick fix, I don't know.

I can't install it on 55.0.3 on my Mac right now:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/17157374/30323083-20f71c66-97bc-11e7-9f54-d1ebdacda03f.png">

I'm not sure if it's really an issue, since everybody else seem to be able to use it. In that case, is there any flag I might have set which is causing the issue?

Thanks,
Altug

**Comment by nt1m** [comment]
Hi @aakay, I've double checked the version info, and the configuration on the add-ons website: I found nothing that seems to block the add-on on 55.

> is there any flag I might have set which is causing the issue?

In about:config, you might want to search for `extensions`, `xpinstall`, and see if there's anything suspicious.

Another thing you can try is setting `extensions.strictCompatibility` to false.

**Comment by aakay** [comment]
Hi Tim, OK, my bad, somehow. I've tried the extension on a fresh installed FF55 and it works. And it's awesome! :) Thanks a lot!

Sorry for the inconvenience.
