### ISSUE TITLE
Support 57+

### ISSUE THREAD

**Issue by navedcoded** [nt1m/vivaldi-fox#49]
Would VivaldiFox be possible using WebExtensions?

**Comment by nt1m** [comment]
> Would VivaldiFox be possible using WebExtensions?

Yes! I am aiming to release the WE sometime next week, hopefully on time for the 57 release.

**Comment by nt1m** [comment]
@navedcoded https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/beta

**Comment by navedcoded** [comment]
I've been testing it, thanks!
