### ISSUE TITLE
Some tab titles look blurry

### ISSUE THREAD

**Issue by ShahedFaisal** [nt1m/vivaldi-fox#52]
Please see the screenshot below.

![2017-11-09 1](https://user-images.githubusercontent.com/13907697/32568597-fc29f89a-c4e8-11e7-8f78-02416677dd31.png)

Browser version: Firefox 57.0
Add-on version: 2.0b1

**Comment by nt1m** [comment]
Thanks for reporting! This a problem with the WebExtensions API: https://bugzilla.mozilla.org/show_bug.cgi?id=1404688

Unfortunately, it probably will be fixed only in 58 or 59.

**Comment by nt1m** [comment]
@ShahedFaisal 

You can work around this by adding this to userChrome.css:
```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

:root, .tabbrowser-tab { 
  text-shadow: none !important; 
}
```
