### ISSUE TITLE
Night mode custom times

### ISSUE THREAD

**Issue by Madis0** [nt1m/vivaldi-fox#54]
The night mode is useful, but I don't want to enable it already on 8 pm... 

Could you add an option to set the start and end time?

**Comment by nt1m** [comment]
Totally agree, I'll try to add that as soon as I can :)

**Comment by nt1m** [comment]
Hi @Madis0, @agriffis, @marsjaninzmarsa 

Here's a beta version with this feature if you're interested in testing this: https://github.com/nt1m/vivaldi-fox/releases/tag/v3.0b1
