### ISSUE TITLE
Theme selector boxes do not open near the dropdown boxes

### ISSUE THREAD

**Issue by fingerwarrior** [nt1m/vivaldi-fox#57]
In the config page, if I try to change the theme with dropdown boes, the lists open somewhere randomly, but stays consistent until I reload the page.

![image](https://user-images.githubusercontent.com/8464592/32865236-478d21d2-ca88-11e7-9508-02f4f4027200.png)

![image](https://user-images.githubusercontent.com/8464592/32865258-5956e40c-ca88-11e7-9b7e-2cbaa0185555.png)

**Comment by nt1m** [comment]
@fingerwarrior Thanks for reporting! This is a Firefox bug that's been fixed in Firefox 58: https://bugzilla.mozilla.org/show_bug.cgi?id=1390445
