### ISSUE TITLE
Doesn't work with HSL

### ISSUE THREAD

**Issue by peiche** [nt1m/vivaldi-fox#61]
Theme color is not applied when the color is in HSL. I created a few demo pages:

[RGB (works)](https://peiche.github.io/VivaldiFoxTest/rgb.html)
[Hex (works)](https://peiche.github.io/VivaldiFoxTest/hex.html)
[HSL (doesn't work)](https://peiche.github.io/VivaldiFoxTest/hsl.html)

It's worth mentioning that Vivaldi does correctly apply the theme color when it's in HSL.

**Comment by nt1m** [comment]
Thanks for reporting!

Seems like my color wrapper doesn't handle HSL atm: https://github.com/nt1m/vivaldi-fox/blob/master/background/color.js#L10

I'll see what I can do

**Comment by nt1m** [comment]
I've fixed this in the latest beta: https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/versions/beta

**Comment by peiche** [comment]
Installed it and confirmed it working. 👍
