### ISSUE TITLE
Color flashes unnecessarily 

### ISSUE THREAD

**Issue by sorin-davidoi** [nt1m/vivaldi-fox#65]
To reproduce, navigate between different subreddits in the same tab. The color is the same (orange) on all subreddits, but it looks like it gets set every time, causing it to become dark for a split second.

Attaching an `mp4` to illustrate the issue. 

[reddit.zip](https://github.com/nt1m/vivaldi-fox/files/1542439/reddit.zip)

**Comment by nt1m** [comment]
Thanks for the screencast! Will check what's going on :)

**Comment by nt1m** [comment]
@sorin-davidoi Does this beta version help? https://github.com/nt1m/vivaldi-fox/releases/tag/v3.0b1
