### ISSUE TITLE
Support dynamic meta theme-color

### ISSUE THREAD

**Issue by sorin-davidoi** [nt1m/vivaldi-fox#70]
Chrome for Android listens for mutations of the `theme-color` meta tag and applies the color to the browser chrome dynamically. An example of a page exhibiting this is [mdBook](https://rust-lang-nursery.github.io/mdBook/README.html) - change the theme from the dropdown and `theme-color` gets updated as well (implementation and screenshots [here](https://github.com/rust-lang-nursery/mdBook/pull/547)). Would be nice if VivaldiFox could support this.

**Comment by agriffis** [comment]
Is this a dup of #36?

**Comment by nt1m** [comment]
Yep.
