### ISSUE TITLE
Option to change the tabs background color instead of the foreground

### ISSUE THREAD

**Issue by pandito** [nt1m/vivaldi-fox#72]
It would be great to have an option to apply the color changing to the window part instead of the bars one just like Vivaldi's themes does.

![captura](https://user-images.githubusercontent.com/26577370/35862056-0acdec18-0b29-11e8-99f8-05d0c8c46174.JPG)
![captura2](https://user-images.githubusercontent.com/26577370/35862057-0afff0be-0b29-11e8-8f46-ff6121592ebe.JPG)

**Comment by nt1m** [comment]
@pandito It's already possible, uncheck "Apply page colors" from the toolbar section and check "Apply page colors" in the frame section, and you should get the same result.

Let me know if it works.

**Comment by pandito** [comment]
oh! It worked perfectly!!

Sorry i didn't see those options.

Thank you
