### ISSUE TITLE
[Question] API to let other extensions know theme color has changed

### ISSUE THREAD

**Issue by Depau** [nt1m/vivaldi-fox#74]
See this issue: https://github.com/freaktechnik/advanced-github-notifier/issues/81

Is there some API other extensions can use to detect whether toolbar icons should be displayed in white or black?

**Comment by nt1m** [comment]
Duplicate of #59 

This should hopefully be solved with https://bugzilla.mozilla.org/show_bug.cgi?id=1441708 fixed
