### ISSUE TITLE
page color lost on refresh

### ISSUE THREAD

**Issue by lcrippa** [nt1m/vivaldi-fox#75]
When I hit the refresh button (or ctrl+R), once the page has finished reloading the page-specific color is lost and defaults to the light (or dark) theme one

**Comment by nt1m** [comment]
@lcrippa Does this beta version help ? https://github.com/nt1m/vivaldi-fox/releases/tag/v3.0b1

**Comment by lcrippa** [comment]
yes, it seems to have fixed it
