### ISSUE TITLE
Cache loaded tabs' colors for instant change

### ISSUE THREAD

**Issue by Madis0** [nt1m/vivaldi-fox#81]
What if VivaldiFox cached all loaded (compared to unloaded) tabs' colors in it's memory, in order to switch them faster when a tab is clicked. That should make the color swap as fast as it is in Vivaldi itself.

A nice bonus would be preloading the colors of loaded, but unvisited background tabs.

**Comment by Madis0** [comment]
[Demo featuring Vivaldi 1.14 and Nightly 61a1](https://streamable.com/j2u2l) (epilepsy warning).

**Comment by nt1m** [comment]
The switch is instant, it's just that Firefox adds a small color transition since Firefox 61: https://bugzilla.mozilla.org/show_bug.cgi?id=1397393

**Comment by nt1m** [comment]
@Madis0 Does the beta version makes things better ? https://github.com/nt1m/vivaldi-fox/releases/tag/v3.0b1

**Comment by Madis0** [comment]
@nt1m It is still fading in, as expected, but it looks smoother than before, which I like.
