### ISSUE TITLE
Add option to enable VivaldiFox only if the page has theme-color set

### ISSUE THREAD

**Issue by 3v1n0** [nt1m/vivaldi-fox#82]
Hey, I love this extension, but I personally only prefer to have this enabled only when the website explicitly defines the colors to use via the meta `theme-color` values.

**Comment by nt1m** [comment]
Fixed by 61d79d2b2256f42bca82a46c44ff836d9e54a427

**Comment by nt1m** [comment]
I've added this in the latest beta version: https://github.com/nt1m/vivaldi-fox/releases/tag/v3.0b1
