### ISSUE TITLE
Window client-side decoration should not be changed on Linux

### ISSUE THREAD

**Issue by Martin1887** [nt1m/vivaldi-fox#83]
In Linux, when VivaldiFox is enabled the icons to minimize, maximize and close the window are changed for window-style icons.

I think that the add-on should not change the window icons (or at least providing an option to preserve them).

**Comment by nt1m** [comment]
I suspect the fix for #52 will fix this too, but leaving this open to be sure.

**Comment by Martin1887** [comment]
It seems fixed.
