### ISSUE TITLE
Black favicons do current tab undistinguishable from inactive tabs

### ISSUE THREAD

**Issue by Martin1887** [nt1m/vivaldi-fox#93]
When the current active tab has a black favicon, it is really difficult knowing which is the active tab.

It could be resolved putting bold the current tab title or making semitransparent the inactive tabs, but in order to not do less readable the inactive tabs maybe this only should be applied on black active tabs.

Another solution would be changing the absolute black for another color when the active tab is black.

Thanks.

**Comment by nt1m** [comment]
@Martin1887 Have you tried the "Enable white background" setting for icons ? This way the icon is always visible.

**Comment by Martin1887** [comment]
I have tried it but it does nothing. I'm using Fedora 28 with Cinnamon 3.8.8.

**Comment by nt1m** [comment]
@Martin1887 The setting doesn't apply to tabs that already exist when you change the setting, it only applies to future tabs you load.

**Comment by Martin1887** [comment]
GitHub is a good example of this issue.

I have tried to open another GitHub tab with this option enabled and it has not worked.

I will remain it enabled and I will close the issue if it works.

**Comment by Martin1887** [comment]
I have tried the option without success.

The GitHub tabs remain black and other sites that were well colored got worse (for instance, the color of Gmail is uglier and the favicon becomes white in some parts making it also uglier).

In conclusion, that option is not a valid workaround for me, although I understand that other issues can have more priority than this one.

**Comment by Martin1887** [comment]
The new tab line color option fix the issue.
