### ISSUE TITLE
Using with Firefox Dark Theme.

### ISSUE THREAD

**Issue by Hummus23** [nt1m/vivaldi-fox#97]
Is there a way to use Dark theme and this add-on together?
Every time I enable one the other stop working.
Firefox dark theme makes the menu, bookmarks and more lists with a dark background.
Thanks.

**Comment by nt1m** [comment]
@Hummus23 You can style the popups to be dark (like in the built-in dark theme) in the Advanced Options.

**Comment by Hummus23** [comment]
For some reason it didn't worked the first time, I changed everything in the Advanced Options.
But now it's working, thanks.

**Comment by Migotes** [comment]
Hummus23: Can you explain your settings please - so it works by me.

Thanks,
Migo

**Comment by Migotes** [comment]
Not by me. I use the Firefox dark theme as standard. Everytime when I open the Firefox new tab, the background is white - also the bookmark sidebar. And yes: I activate the dark mode in VivaldiFox.

Have anybody any idea?

**Comment by Pablo1107** [comment]
@Migotes yes, I think there is a problem with how the dark theme is implemented. For example, if you go to the customize page, the background is always white.

**Comment by DaniellMesquita** [comment]
@nt1m
